name: DL Data Parser - CI Tests

on: [push]

jobs:
  pytest:
    name: Run tests

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2

      - name: Install required packages
        run: |
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest --slow
