name: DL Data Parser - CI Tests

on: [push]

jobs:
  pytest:
    name: Run tests

    runs-on: windows-latest

    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2

      - name: Install required packages
        run: |
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest
